noto-styles class: fix FILES list of per-style packages
Specifying ".ttf" file suffix in FILES pattern left out .otf fonts,
which was caught in installed-vs-shipped QA check.

For example,

  ERROR: noto-sans-thai-2.002-r0 do_package: QA Issue: noto-sans-thai:
    Files/directories were installed but not shipped in any package:
    /usr/share/fonts/opentype/noto/NotoSansThai-ExtraCondensedExtraLight.otf
    /usr/share/fonts/opentype/noto/NotoSansThai-ExtraBold.otf
    ...

Signed-off-by: Geoff Parker <geoffrey.parker@arthrex.com>